### ISSUE TITLE
Invalid or corrupt jarfile jquery-3.6.1.min.js

### ISSUE THREAD

**Issue by pauldresen** [git-ZeR0/Senec_Log_Viewer#1]
Senec_Log_Viewer funktioniert nicht. Wahrscheinlich liegt es an

Invalid or corrupt jarfile jquery-3.6.1.min.js

beim Aufruf mit java -jar

java -version
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 21.0.2+13-Ubuntu-122.04.1, mixed mode, sharing)

**Comment by Pr1smBr34k3r** [comment]
jquery-3.6.1.min.js hatte den falschen inhalt. Dies sollte nun behoben sein.
